# Generated by Django 6.0.1 on 2026-01-19 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribed_journalists',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups_name': 'Journalist'}, related_name='journalist_followers', to=settings.AUTH_USER_MODEL, verbose_name='followed journalists'),
        ),
    ]
