# Generated by Django 6.0.1 on 2026-01-26 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='notifications_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscribed_journalists',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Journalist'}, related_name='journalist_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
