# Generated by Django 6.0.1 on 2026-01-29 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_article_notifications_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('api_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='The reader account whose subscriptions this API client can access', limit_choices_to={'groups__name': 'Reader'}, on_delete=django.db.models.deletion.CASCADE, related_name='api_clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
