# Generated by Django 6.0.1 on 2026-01-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_apiclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiclient',
            name='api_key',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
    ]
