# Generated by Django 6.0.1 on 2026-01-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_apiclient_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiclient',
            name='api_key',
            field=models.CharField(blank=True, editable=False, help_text='Long random token used for API authentication', max_length=64, unique=True),
        ),
    ]
